//! Multi-transaction plans.
//!
//! Some flows genuinely do not fit in one transaction. A confidential transfer
//! on a fee-bearing mint needs five zero-knowledge proofs; a single range proof
//! alone is larger than the 1232-byte packet limit, so each proof is verified
//! into its own *context state account* in its own transaction and the transfer
//! then just references those accounts.
//!
//! Rather than hide that behind a "send everything" helper, the builders return
//! an ordered list of [`Step`]s. Each step is exactly one transaction and
//! carries the set of signers it needs, which is also where the authority model
//! becomes visible: creating an associated token account needs only a payer,
//! while `ConfigureAccount` needs the account *owner*.

use {solana_instruction::Instruction, solana_pubkey::Pubkey};

/// One transaction's worth of work.
#[derive(Debug, Clone)]
pub struct Step {
    /// Human-readable name, handy in logs and test failures.
    pub label: &'static str,
    /// Instructions, in order. Send them as a single transaction: proof
    /// instructions placed inline are located by *relative offset*, so
    /// splitting a step breaks it.
    pub instructions: Vec<Instruction>,
    /// Signers this step requires beyond the fee payer. An ephemeral keypair
    /// listed here (a new mint, a proof context account) must be generated by
    /// the caller and is named in the step's instructions.
    pub signers: Vec<Pubkey>,
}

impl Step {
    pub fn new(label: &'static str, instructions: Vec<Instruction>, signers: Vec<Pubkey>) -> Self {
        Self {
            label,
            instructions,
            signers,
        }
    }

    /// A step that only the fee payer needs to sign.
    pub fn payer_only(label: &'static str, instructions: Vec<Instruction>) -> Self {
        Self::new(label, instructions, Vec::new())
    }
}
